version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - php
  db:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravellogin
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_PASSWORD: 12345678
      MYSQL_USER: laravel
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - php
    ports:
      - "3306:3306"  # เพิ่มบรรทัดนี้
networks:
  php:
    driver: bridge
volumes:
  dbdata:
    driver: local